export interface Technology {
  name: string;
  img: string;
}

export const TECHNOLOGIES: Record<string, Technology> = {
  angular: { name: "Angular", img: "/images/icons/angular.svg" },
  atlassian: { name: "Atlassian", img: "/images/icons/atlassian.svg" },
  aws: { name: "AWS", img: "/images/icons/aws.svg" },
  awscdk: { name: "AWS CDK", img: "/images/icons/aws-cdk.svg" },
  chatgpt: { name: "ChatGPT", img: "/images/icons/chatgpt.svg" },
  claude: { name: "Claude", img: "/images/icons/claude.svg" },
  copilot: { name: "Copilot", img: "/images/icons/copilot.svg" },
  cpp: { name: "C++", img: "/images/icons/cpp.svg" },
  csharp: { name: "C#", img: "/images/icons/csharp.svg" },
  css: { name: "CSS", img: "/images/icons/css.svg" },
  datadog: { name: "Datadog", img: "/images/icons/datadog.svg" },
  discordjs: { name: "Discord.js", img: "/images/icons/discordjs.svg" },
  docker: { name: "Docker", img: "/images/icons/docker.svg" },
  expo: { name: "Expo", img: "/images/icons/expo.svg" },
  git: { name: "Git", img: "/images/icons/git.svg" },
  github: { name: "GitHub", img: "/images/icons/github.svg" },
  graphql: { name: "GraphQL", img: "/images/icons/graphql.svg" },
  hono: { name: "Hono", img: "/images/icons/hono.svg" },
  html: { name: "HTML", img: "/images/icons/html.svg" },
  insomnia: { name: "Insomnia", img: "/images/icons/insomnia.svg" },
  java: { name: "Java", img: "/images/icons/java.svg" },
  javascript: {
    name: "JavaScript",
    img: "/images/icons/javascript.svg",
  },
  jest: { name: "Jest", img: "/images/icons/jest.svg" },
  labview: { name: "LabVIEW", img: "/images/icons/labview.svg" },
  launchdarkly: {
    name: "LaunchDarkly",
    img: "/images/icons/launchdarkly.svg",
  },
  linux: { name: "Linux", img: "/images/icons/linux.svg" },
  mysql: { name: "MySQL", img: "/images/icons/mysql.svg" },
  neon: { name: "Neon", img: "/images/icons/neon.svg" },
  nestjs: { name: "NestJS", img: "/images/icons/nestjs.svg" },
  nextjs: { name: "Next.js", img: "/images/icons/nextjs.svg" },
  nodejs: { name: "Node.js", img: "/images/icons/nodejs.svg" },
  python: { name: "Python", img: "/images/icons/python.svg" },
  qt: { name: "Qt", img: "/images/icons/qt.svg" },
  react: { name: "React", img: "/images/icons/react.svg" },
  redis: { name: "Redis", img: "/images/icons/redis.svg" },
  sentry: { name: "Sentry", img: "/images/icons/sentry.svg" },
  sequelize: { name: "Sequelize", img: "/images/icons/sequelize.svg" },
  shadcn: { name: "Shadcn", img: "/images/icons/shadcn.svg" },
  sqlite: { name: "SQLite", img: "/images/icons/sqlite.svg" },
  stytch: { name: "Stytch", img: "/images/icons/stytch.png" },
  tableau: { name: "Tableau", img: "/images/icons/tableau.svg" },
  tailwind: { name: "Tailwind", img: "/images/icons/tailwind.svg" },
  threejs: { name: "Three.js", img: "/images/icons/threejs.svg" },
  twilio: { name: "Twilio", img: "/images/icons/twilio.svg" },
  typescript: {
    name: "TypeScript",
    img: "/images/icons/typescript.svg",
  },
  unity: { name: "Unity", img: "/images/icons/unity.svg" },
  v0: { name: "V0", img: "/images/icons/v0.svg" },
  vercel: { name: "Vercel", img: "/images/icons/vercel.svg" },
  vite: { name: "Vite", img: "/images/icons/vite.svg" },
  vitest: { name: "Vitest", img: "/images/icons/vitest.svg" },
  vs: { name: "Visual Studio", img: "/images/icons/vs.svg" },
  vscode: { name: "VS Code", img: "/images/icons/vscode.svg" },
  vue: { name: "Vue", img: "/images/icons/vue.svg" },
  windows: { name: "Windows", img: "/images/icons/windows.svg" },
  workos: { name: "WorkOS", img: "/images/icons/workos.svg" },
  wpf: { name: "WPF", img: "/images/icons/wpf.svg" },
  xamarin: { name: "Xamarin", img: "/images/icons/xamarin.svg" },
};
